### PR TITLE
added tailwindcss to deps, including yarn.lock

### PR DESCRIPTION
**Pull request by newtmitch**
Project was missing tailwindcss dependency so it wouldn't start. I also included yarn.lock as there was no lockfile present at all. Let me know if that was intentional and I can remove that and resubmit the PR.

### CODE REVIEW

**Comment by slamethendry** [comment]
Hi
My local set up only needed astro/tailwind in devDependencies and seems a few other people are fine also. But I am happy to add tailwindcss to dependencies if that makes it smoother for everyone to use the project.

However, I prefer not to commit lockfile in the git repo, if that is okay for you to resubmit.

Thanks a bunch!

**Comment by newtmitch** [comment]
I'll check again and see if adding tailwind into devDeps works and submit it there if so if that's your preference. It wasn't in devDeps in the repo either, so I think it needs to be somewhere, devDeps or deps, whichever makes sense.

I'll also remove the lock file and resubmit. I'll try to get that done in the next couple of days.

**Comment by slamethendry** [comment]
It is in the devDeps. See https://github.com/slamethendry/TinyRocket/blob/main/package.json, line 15.
`"@astrojs/tailwind": "^5.0.0",`

But I do not use yarn at all so I cannot check with yarn. And I don't know enough why it did not start for you.

Cheers.

**Comment by newtmitch** [comment]
I think that devdep is only for the Astro integration with tailwind, it doesn't include tailwind itself, which is why it didn't start for me. When I stamped out this template it wouldn't start until I added Tailwind as a dep. I'll double-check, though, before I resubmit the PR.

Update - see my comment below: https://github.com/slamethendry/TinyRocket/pull/9#issuecomment-1773828943

**Comment by newtmitch** [comment]
Just for completeness' sake, here's the error I see after running `yarn install` and `yarn dev` on the repo's `main` branch:

```
❯ yarn dev
yarn run v1.22.19
$ astro dev
10:00:06 AM [vite] Error when evaluating SSR module /Users/mitch/Dev/reference-only/astro-blog-template-personal-eval/tiny-rocket/astro.config.mjs: failed to import "@astrojs/tailwind"
|- Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'tailwindcss' imported from /Users/mitch/Dev/reference-only/astro-blog-template-personal-eval/tiny-rocket/node_modules/@astrojs/tailwind/dist/index.js
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:887:9)
    at moduleResolve (node:internal/modules/esm/resolve:936:20)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)

[astro] Unable to load your Astro config

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /Users/mitch/Dev/reference-only/astro-blog-template-personal-eval/tiny-rocket): [Error] Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'
Require stack:
- /Users/mitch/Dev/reference-only/astro-blog-template-personal-eval/tiny-rocket/postcss.config.cjs

(@/Users/mitch/Dev/reference-only/astro-blog-template-personal-eval/tiny-rocket/postcss.config.cjs)
Error: Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'
Require stack:
- /Users/mitch/Dev/reference-only/astro-blog-template-personal-eval/tiny-rocket/postcss.config.cjs

(@/Users/mitch/Dev/reference-only/astro-blog-template-personal-eval/tiny-rocket/postcss.config.cjs)
    at load (file:///Users/mitch/Dev/reference-only/astro-blog-template-personal-eval/tiny-rocket/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:36429:11)
    at file:///Users/mitch/Dev/reference-only/astro-blog-template-personal-eval/tiny-rocket/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:36454:16
    at Array.map (<anonymous>)
    at plugins (file:///Users/mitch/Dev/reference-only/astro-blog-template-personal-eval/tiny-rocket/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:36453:8)
    at processResult (file:///Users/mitch/Dev/reference-only/astro-blog-template-personal-eval/tiny-rocket/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:36523:14)
    at file:///Users/mitch/Dev/reference-only/astro-blog-template-personal-eval/tiny-rocket/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:36647:14]

Node.js v18.17.1
error Command failed with exit code 1.
```

See my comment below, but it appears that `npm` is installing `tailwindcss` as a peer dep from `@astrojs/tailwind@5.0.2` where `yarn` is not. I don't know why yet.

**Comment by newtmitch** [comment]
This is really interesting. I tested with `npm` instead of `yarn` just to make sure the problem was present on both sides and `npm` installs tailwind as a dependency of `@astro/tailwind` so the problem doesn't show up at all there. That's likely why you're not seeing this issue, given that you don't use yarn. I've never seen this kind of discrepancy between package managers before. Let me dig a touch more. Since you don't include `package-lock.json` in your repo, yarn can't use that as a basis to migrate to yarn and build its `yarn.lock` file, so it's missing that dependency on its own. Very strange.

**update:** I did some digging, and npm automatically installs peer deps (version 7 or later), yarn 1.x does not. I'm still using Yarn 1.x. Although this was addressed in yarn v2 (see https://github.com/yarnpkg/yarn/issues/8011) in 2021, it looks like the Yarn 2+ world is a completely different thing package-management-wise and I'm not up-to-date on that approach. It does _not_ look like a simple update, although largely compatible with existing the package.json approach, it doesn't (by default) use `node_modules` at all.

That said, installing with the latest version of Yarn (3.6.4) throws errors as well (although apparently about another unmet peer dep), so this isn't simply an issue of upgrading Yarn to something more recent. 

@slamethendry I think this is, at this point, a question of how you want to manage your repo. Because you don't have a lock file at all (`npm` or `yarn`) and no specific installation instructions in your README that I saw, your repo suggests that you're agnostic to package management tooling. However, it won't work for `yarn` because you're missing a peer dependency that yarn won't install implicitly like `npm` does. That means it looks broken to `yarn`-default users (such as myself). I'm happy to close this PR if you prefer to leave it that way, but it did create a hurdle in my own evaluation of this template that you might not want to put in front of your users - your call there. It certainly wouldn't hurt to add the explicit Tailwind dependency other than requiring you to keep it up to date with the rest of the deps. I'm going to resubmit the PR without the lockfile regardless. Let me know how you'd like to proceed. 

**interesting side note:** installing the latest version of yarn on my Mac via Homebrew still installs the 1.x version, so it appears it's still somewhat relevant even with the later versions being out there. I was afraid I was insanely out of date with my tooling here, but I think Yarn might be just going in a very different direction so I might need to reevaluate my built-in preference for it over `npm` and figure out what the way forward is. :)

**Comment by newtmitch** [comment]
I just modified the upstream branch and removed `yarn.lock`, rebased and force-pushed the branch.

**Review by slamethendry — APPROVED** [review]

**Pull request merged**
